AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 80

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false # for now

Metrics/AbcSize:
  Exclude:
    - test/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb
