name: build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle lock --add-platform x86_64-linux
    - run: bundle install
    - run: bundle exec rake
